ft: improve curlit

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -135,6 +135,8 @@ alias gconf="lvim ~/.gitconfig"
 alias tconf="lvim ~/.tmux.conf"
 alias iconf="lvim ~/dotfiles/i3/config"
 alias lconf="lvim ~/.config/lvim/config.lua"
+alias ldconf="lvim ~/.config/lazydocker/config.yml"
+alias lgconf="lvim ~/.config/lazygit/config.yml"
 alias dockit="vim ~/dotfiles/zsh/custom/plugins/dockit/dockit.plugin.zsh"
 alias szsh="source ~/.zshrc"
 alias k="kubectl"
@@ -178,67 +180,67 @@ function jwt_decode(){
 
 function curlit() {
 
-usage() {
-  echo "Usage: $(basename "$0") [-j <jq_query>] [-d <string>] [-h]" >&2
-  echo "Options:" >&2
-  echo "  -j <jq_query>    JQ query to filter input" >&2
-  echo "  -d <variable>    Variable to save query result" >&2
-  echo "  -h               Print usage instructions" >&2
-}
+  usage() {
+    echo "Usage: $(basename "$0") [-j <jq_query>] [-d <string>] [-h]" >&2
+    echo "Options:" >&2
+    echo "  -j <jq_query>    JQ query to filter input" >&2
+    echo "  -d <variable>    Variable to save query result" >&2
+    echo "  -h               Print usage instructions" >&2
+  }
 
-local jq_query=""
-local variable=""
+  local jq_query=""
+  local variable=""
 
-while getopts ":j:d:h" opt; do
-  case ${opt} in
-    j )
-      jq_query="$OPTARG"
-      ;;
-    d )
-      variable="$OPTARG"
-      ;;
-    h )
-      usage
-      return 0
-      ;;
-    \? )
-      echo "Invalid option: -$OPTARG" >&2
-      usage
-      return 1
-      ;;
-    : )
-      echo "Option -$OPTARG requires an argument." >&2
-      usage
-      return 1
-      ;;
-  esac
-done
+  while getopts ":j:d:h" opt; do
+    case ${opt} in
+      j )
+        jq_query="$OPTARG"
+        ;;
+      d )
+        variable="$OPTARG"
+        ;;
+      h )
+        usage
+        return 0
+        ;;
+      \? )
+        echo "Invalid option: -$OPTARG" >&2
+        usage
+        return 1
+        ;;
+      : )
+        echo "Option -$OPTARG requires an argument." >&2
+        usage
+        return 1
+        ;;
+    esac
+  done
 
-if [ -n "$variable" ] && [ -z "$jq_query" ]; then
-  echo "Error: You must pass the -j flag when using the -d flag" >&2
-  usage
-  return 1
-fi
+  if [ -n "$variable" ] && [ -z "$jq_query" ]; then
+    echo "Error: You must pass the -j flag when using the -d flag" >&2
+    usage
+    return 1
+  fi
 
-local body="$(cat)"
+  local body="$(cat)"
 
-echo "$body" | awk '/^HTTP/{if($2~/2../)print "\033[32m"$0"\033[0m"; else if($2~/3../)print "\033[33m"$0"\033[0m"; else if($2~/4../)print "\033[31m"$0"\033[0m"; else if($2~/5../)print "\033[35m"$0"\033[0m"; else print}'
-echo "$body" | sed '1,/^\r$/d'| jq '. as $raw | try fromjson catch $raw '
+  echo "$body" | awk '/^HTTP/{if($2~/2../)print "\033[32m"$0"\033[0m"; else if($2~/3../)print "\033[33m"$0"\033[0m"; else if($2~/4../)print "\033[31m"$0"\033[0m"; else if($2~/5../)print "\033[35m"$0"\033[0m"; else print}'
+  echo "$body" | sed '1,/^\r$/d'| jq -r '. as $raw | try fromjson catch $raw '
 
-status_code=$(echo "$body" | awk '/^HTTP/{print $2}')
-if [ "$status_code" != "200" ]; then
-return 1
-fi
+  status_code=$(echo "$body" | awk '/^HTTP/{print $2}')
+  if [ "$status_code" != "200" ]; then
+    return 1
+  fi
 
-if [ -n "$jq_query" ] && [ -n "$variable" ]; then
-  echo "$body" | sed '1,/^\r$/d'| jq -r "$jq_query" > "$variable"
-  return 0
-fi
+  if [ -n "$jq_query" ] && [ -n "$variable" ]; then
+    echo "$body" | sed '1,/^\r$/d'| jq -r "$jq_query" > "$variable"
+    return 0
+  fi
 
-if [ -n "$jq_query" ]; then
-  echo "$body" | sed '1,/^\r$/d'| jq -r "$jq_query"
-  return 0
-fi
+  if [ -n "$jq_query" ]; then
+    echo "$body" | sed '1,/^\r$/d'| jq -r "$jq_query"
+    return 0
+  fi
 
 }
 
